services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PWD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${DB_PORT}:3306"
    #volumes:
    #  - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-p${DB_PWD}" ]
      interval: 10s
      timeout: 2s
      retries: 2
    networks:
      - backend

  redis:
    image: redis:7.2
    container_name: redis-container
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 2s
      retries: 2
    networks:
      - backend

  app:
    build:
      context: .  # Dockerfile 위치
    image: chichi-app:latest
    container_name: chichi-spring-app
    depends_on:
      - mysql
      - redis
    environment:
      DB_HOST: mysql
      REDIS_HOST: redis
      DB_NAME: ${DB_NAME}
      DB_PWD: ${DB_PWD}
      DB_USER: ${DB_USER}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "${SPRING_PORT}:8080"
    networks:
      - backend

volumes:
  mysql-data:

networks:
  backend:
