services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PWD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${MYSQL_PORT}:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-p${DB_PWD}" ]
      interval: 10s
      timeout: 2s
      retries: 2
    networks:
      - backend

  redis:
    image: redis:7.2
    container_name: redis-container
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 2s
      retries: 2
    networks:
      - backend

  app-blue:
    build:
      context: .
    container_name: app-blue
    image: chichi-app:latest
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      COLOR: blue
      DB_HOST: mysql
      REDIS_HOST: redis
      DB_NAME: ${DB_NAME}
      DB_PWD: ${DB_PWD}
      DB_USER: ${DB_USER}
      JWT_SECRET: ${JWT_SECRET}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
      DISCORD_REDIRECT_URI: ${DISCORD_REDIRECT_URI}
    ports:
      - "8081:8080"
    networks:
      - backend

networks:
  backend:
